server:
  servlet:
    contextpath: /api

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://0.0.0.0:5432/postgres
    username: postgres
    password: password
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
flyway:
  url: jdbc:postgresql://0.0.0.0:5432/postgres
  schemas: public
  user: postgres
  password: password
  validateMigrationNaming: true
