spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    platform: postgres
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:15.1:///test_db
    username: user
    password: pass
  jpa:
    show-sql: true
    deferDatasourceInitialization: false
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    flyway:
      enabled: false
flyway:
  url: jdbc:tc:postgresql:15.1:///test_db
  schemas: public
  username: user
  password: pass
  validateMigrationNaming: true