version: '3.5'

services:
  spring-api:
    container_name: spring-api
    image: petrutarna/time-tracking-api:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-postgres}
      SPRING_DATASOURCE_USER: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - 8080:8080
    networks:
      - postgres-ntw
    depends_on:
      - "postgres"

  postgres:
    container_name: postgres_db
    image:  
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - 5432:5432
    networks:
      - postgres-ntw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  

networks:
  postgres-ntw:
    driver: bridge