/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-web:2.7.4")
    api("org.springframework.boot:spring-boot-starter-data-jpa:2.7.4")
    api("org.springframework.boot:spring-boot-starter-validation:2.7.4")
    api("org.flywaydb:flyway-core:8.5.13")
    api("io.springfox:springfox-boot-starter:3.0.0")
//    api("org.projectlombok:lombok:1.18.24")
    api("io.jsonwebtoken:jjwt-api:0.11.5")
    api("com.googlecode.json-simple:json-simple:1.1.1")
    api("javax.xml.bind:jaxb-api:2.3.1")
    runtimeOnly("org.postgresql:postgresql:42.3.7")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:2.7.4")
    runtimeOnly("io.jsonwebtoken:jjwt-impl:0.11.5")
    runtimeOnly("io.jsonwebtoken:jjwt-jackson:0.11.5")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.4")
    testImplementation("org.testcontainers:testcontainers:1.17.5")
    testImplementation("org.testcontainers:postgresql:1.17.5")
    compileOnly("org.projectlombok:lombok:1.18.24")
    annotationProcessor("org.projectlombok:lombok:1.18.24")
}

group = "com.example"
version = "0.0.1-SNAPSHOT"
description = "time-traking"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
